<?php defined('ABSPATH') or die('Cheatin\' uh?');
/**
 * Returns the CSF field definitions for the what-we-do section instance.
 * @return array
 */
function mthan_section_what_we_do_options()
{
    return array(
        mthan_subtitle_field('What We Do'),
        array(
            'id' => 'wwd_subtitle_icon',
            'type' => 'media',
            'library' => 'image',
            'preview' => false,
            'title' => 'Subtitle Icon',
            'default' => array('url' => get_template_directory_uri() . '/assets/images/icons/leaf-two.png')
        ),
        mthan_title_field('Special Services For You'),
            array(
            'id' => 'tabs_repeater',
            'type' => 'group',
            'title' => 'Services Tabs',
            'max' => 5,
            'fields' => array(
                    mthan_name_field(),
                    mthan_icon_field(),
                    array(
                        'id'    => 'hover_icon',
                        'type'  => 'text',
                        'title' => 'Hover / Content Icon Class',
                    ),
                    array(
                    'id' => 'bg_image',
                    'type' => 'media',
                    'library' => 'image',
                    'preview' => false,
                    'title' => 'Background Image (Left)',
                ),
                    array(
                    'id' => 'box_title',
                    'type' => 'text',
                    'title' => 'Project Box Title',
                    'default' => "Let's Start Your Project",
                ),
                    array(
                    'id' => 'box_text',
                    'type' => 'text',
                    'title' => 'Project Box Text',
                    'default' => 'Make an appointment & Start your project today.',
                ),
                    mthan_btn_text_field('Appointment', 'Project Box Button Text', 'box_btn_text'),
                    mthan_btn_link_field('', 'Project Box Button Link', 'box_btn_link'),
                    array(
                    'id' => 'content_subtitle',
                    'type' => 'text',
                    'title' => 'Content Subtitle',
                    'default' => 'know About',
                ),
                    array(
                    'id' => 'content_title',
                    'type' => 'text',
                    'title' => 'Content Title',
                ),
                    array(
                    'id' => 'content_text',
                    'type' => 'textarea',
                    'title' => 'Content Text',
                ),
                    array(
                    'id' => 'bro_thumb',
                    'type' => 'media',
                    'library' => 'image',
                    'preview' => false,
                    'title' => 'Brochure Thumb',
                ),
                    array(
                    'id' => 'bro_title',
                    'type' => 'text',
                    'title' => 'Brochure Title',
                    'default' => 'Projects & Case Studies',
                ),
                    array(
                    'id' => 'bro_link_text',
                    'type' => 'text',
                    'title' => 'Brochure Link Text',
                    'default' => 'Download.pdf',
                ),
                    array(
                    'id' => 'bro_link_url',
                    'type' => 'text',
                    'title' => 'Brochure Link URL',
                    'default' => '#',
                ),
                    array(
                    'id' => 'more_link_text',
                    'type' => 'text',
                    'title' => 'More Link Text',
                    'default' => 'More about service',
                ),
                    array(
                    'id' => 'more_link_url',
                    'type' => 'text',
                    'title' => 'More Link URL',
                    'default' => '#',
                ),
            ),
            'default' => array(
                    array(
                    'name' => 'Spring Cleanup',
                    'icon' => 'flaticon-hedge',
                    'bg_image' => array('url' => get_template_directory_uri() . '/assets/images/background/image-1.jpg'),
                    'box_title' => "Let's <br>Start Your Project",
                    'box_text' => 'Make an appointment & Start your project today.',
                    'box_btn_text' => 'Appointment',
                    'box_btn_link' => '#',
                    'content_subtitle' => 'know About',
                    'content_title' => 'Spring Cleanup',
                    'content_text' => 'We denounce with righteous indignation and dislike men who are beguiled and demoralized by the charms of pleasure of the moment equal belongs fail in their duty through as saying through shrinking ...',
                    'bro_thumb' => array('url' => get_template_directory_uri() . '/assets/images/resource/bro-thumb-1.jpg'),
                    'bro_title' => 'Projects & Case Studies',
                    'bro_link_text' => 'Download.pdf',
                    'bro_link_url' => '#',
                    'more_link_text' => 'More about service',
                    'more_link_url' => '#',
                ),
                    array(
                    'name' => 'Plants Plantintg',
                    'icon' => 'flaticon-digging-1',
                    'bg_image' => array('url' => get_template_directory_uri() . '/assets/images/background/image-2.jpg'),
                    'box_title' => "Let's <br>Start Your Project",
                    'box_text' => 'Make an appointment & Start your project today.',
                    'box_btn_text' => 'Appointment',
                    'box_btn_link' => '#',
                    'content_subtitle' => 'know About',
                    'content_title' => 'Plants Plantintg',
                    'content_text' => 'We denounce with righteous indignation and dislike men who are beguiled and demoralized by the charms of pleasure of the moment equal belongs fail in their duty through as saying through shrinking ...',
                    'bro_thumb' => array('url' => get_template_directory_uri() . '/assets/images/resource/bro-thumb-1.jpg'),
                    'bro_title' => 'Projects & Case Studies',
                    'bro_link_text' => 'Download.pdf',
                    'bro_link_url' => '#',
                    'more_link_text' => 'More about service',
                    'more_link_url' => '#',
                ),
                    array(
                    'name' => 'Water Fountain',
                    'icon' => 'flaticon-sprinkler',
                    'bg_image' => array('url' => get_template_directory_uri() . '/assets/images/background/image-3.jpg'),
                    'box_title' => "Let's <br>Start Your Project",
                    'box_text' => 'Make an appointment & Start your project today.',
                    'box_btn_text' => 'Appointment',
                    'box_btn_link' => '#',
                    'content_subtitle' => 'know About',
                    'content_title' => 'Water Fountain',
                    'content_text' => 'We denounce with righteous indignation and dislike men who are beguiled and demoralized by the charms of pleasure of the moment equal belongs fail in their duty through as saying through shrinking ...',
                    'bro_thumb' => array('url' => get_template_directory_uri() . '/assets/images/resource/bro-thumb-1.jpg'),
                    'bro_title' => 'Projects & Case Studies',
                    'bro_link_text' => 'Download.pdf',
                    'bro_link_url' => '#',
                    'more_link_text' => 'More about service',
                    'more_link_url' => '#',
                ),
                    array(
                    'name' => 'Hard Scaping',
                    'icon' => 'flaticon-painting',
                    'bg_image' => array('url' => get_template_directory_uri() . '/assets/images/background/image-4.jpg'),
                    'box_title' => "Let's <br>Start Your Project",
                    'box_text' => 'Make an appointment & Start your project today.',
                    'box_btn_text' => 'Appointment',
                    'box_btn_link' => '#',
                    'content_subtitle' => 'know About',
                    'content_title' => 'Hard Scaping',
                    'content_text' => 'We denounce with righteous indignation and dislike men who are beguiled and demoralized by the charms of pleasure of the moment equal belongs fail in their duty through as saying through shrinking ...',
                    'bro_thumb' => array('url' => get_template_directory_uri() . '/assets/images/resource/bro-thumb-1.jpg'),
                    'bro_title' => 'Projects & Case Studies',
                    'bro_link_text' => 'Download.pdf',
                    'bro_link_url' => '#',
                    'more_link_text' => 'More about service',
                    'more_link_url' => '#',
                ),
                    array(
                    'name' => 'Garden Care',
                    'icon' => 'flaticon-wheelbarrow',
                    'bg_image' => array('url' => get_template_directory_uri() . '/assets/images/background/image-5.jpg'),
                    'box_title' => "Let's <br>Start Your Project",
                    'box_text' => 'Make an appointment & Start your project today.',
                    'box_btn_text' => 'Appointment',
                    'box_btn_link' => '#',
                    'content_subtitle' => 'know About',
                    'content_title' => 'Garden Care',
                    'content_text' => 'We denounce with righteous indignation and dislike men who are beguiled and demoralized by the charms of pleasure of the moment equal belongs fail in their duty through as saying through shrinking ...',
                    'bro_thumb' => array('url' => get_template_directory_uri() . '/assets/images/resource/bro-thumb-1.jpg'),
                    'bro_title' => 'Projects & Case Studies',
                    'bro_link_text' => 'Download.pdf',
                    'bro_link_url' => '#',
                    'more_link_text' => 'More about service',
                    'more_link_url' => '#',
                ),
            ),
        ),
    );
}
